spring:
  application:
    name: gateway

  data:
    redis:
      host: redis        # ðŸ‘ˆ Service name
      port: 6379
      password: 12345

#  cloud:
#    gateway:
#      server:
#        webflux:
#          routes:
#            - id: auth
#              uri: http://auth:4081
#              predicates:
#                - Path=/auth/**
#              filters:
#                - name: RequestRateLimiter
#                  args:
#                    redis-rate-limiter.replenishRate: 1
#                    redis-rate-limiter.burstCapacity: 5
#                    key-resolver: "#{@ipKeyResolver}"
#            - id: user
#              uri: http://user:4082
#              predicates:
#                - Path=/users/**
#              filters:
#                - name: RequestRateLimiter
#                  args:
#                    redis-rate-limiter.replenishRate: 1
#                    redis-rate-limiter.burstCapacity: 5
#                    key-resolver: "#{@userKeyResolver}"
#          discovery:
#            locator:
#              enabled: false
